# Starship.rs Config File

# Main structure
format = """$os\
$username\
$hostname\
$package\
$cmd_duration\
$fill\
$python\
$golang\
$nodejs\
$rust\
$git_branch\
$git_status\
$jobs\
$shell\
$line_break\
$directory\
$character
"""

palette = "everforest"

# Everforest color palette for Starship
[palettes.everforest]
background = "#2b3339"
foreground = "#d3c6aa"
black = "#323d43"
red = "#e67e80"
green = "#a7c080"
yellow = "#d8a657"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
bold_black = "#4c555b"
bold_red = "#f85552"
bold_green = "#a7c080"
bold_yellow = "#e6c181"
bold_blue = "#7fbbb3"
bold_magenta = "#d699b6"
bold_cyan = "#83c092"
bold_white = "#d3c6aa"

# OS Info
[os]
disabled = false
style = 'bold green'
format = '[$symbol ]($style)'

# OS Logo
[os.symbols]
Windows = "[ó°²](bold green)"
Ubuntu = "[ïŒœ](bold red)"
SUSE = "[ïŒ”](bold green)"
Mint = "[ó°£­](bold green)"
Linux = "[ó°Œ½](bold yellow)"
Gentoo = "[ó°£¨](bold white)"
Fedora = "[ó°£›](bold green)"
Alpine = "[ïŒ€](bold yellow)"
Android = "[îœŽ](bold red)"
Arch = "[ó°£‡](bold green)"
Debian = "[ó°£š](bold red)"

# Username
[username]
show_always = true
style_user = "white bold"
style_root = "red bold"
format = '[$user]($style)'

# Hostname
[hostname]
ssh_only = false
format = '[ [>](bold yellow) [$hostname](bold yellow) [>](bold yellow) ]($style)'

# Git Branch
[git_branch]
symbol = "ï˜ "
format = ' [\[ $symbol $branch \]](bold green)'

# Git Status
[git_status]
format = '[(\[ $all_status$ahead_behind \])](bold green)'

# Command Duration
[cmd_duration]
min_time = 75
format = '[$duration](bold yellow)'

# Line Break
[line_break]
disabled = false

# Bar extender
[fill]
symbol = ' '

# Current Directory
[directory]
style = "white bold"
format = "[$path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

# Character
[character]
disabled = false
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

# Package
[package]
symbol = "ðŸ“¦"
style = "bold yellow"
format = '[$symbol $version]($style)'

# Shell
[shell]
bash_indicator = 'î¯Š bash'
fish_indicator = "ó°ˆº fish"
zsh_indicator = "ó°¬‡ zsh"
powershell_indicator = "ó°¨Š pwsh"
unknown_indicator = "îš‘ shell"
style = "bold green"
format = '[$indicator]($style)'
disabled = false

# NodeJS
[nodejs]
symbol = "ó°Ž™ "
style = "bold green"
format = '[$symbol ($version) ]($style)'

# Python
[python]
symbol = "îœ¼ "
style = "bold green"
format = '[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)'

# Rust
[rust]
symbol = "ó±˜— "
style = "bold yellow"
format = '[$symbol ($version)]($style)'

# GoLang
[golang]
symbol = "ó°Ÿ“ "
style = "bold green"
format = '[$symbol ($version)]($style)'
