#----------------------------------------------------------
# ðŸŒ² Everforest Starship Custom Theme ðŸŒ²
# âš™ï¸  Made by Mingfei âš™ï¸
# Github: https://github.com/MingFei2001
#----------------------------------------------------------
# Main structure
format = """
$os\
$username\
$hostname\
$git_branch\
$git_status\
$cmd_duration\
[|+++>](bold #A6B0A0)\
$fill\
[<+++|](bold #A6B0A0)\
$time\
$line_break\
$directory\
$character
"""
#----------------------------------------------------------
# OS Info
[os]
disabled = false
style = 'bold #A6B0A0'
format = '[$symbol ]($style)'
# OS Logo variants
[os.symbols]
Windows = "ó°²"
Ubuntu = "ïŒœ "
SUSE = "ïŒ”"
Mint = "ó°£­"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Android = "îœŽ"
Arch = "ó°£‡"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
#----------------------------------------------------------
# User info
# Username
[username]
show_always = true
style_user = "#7FBBB3 bold"
style_root = "red bold"
format = '[$user]($style)'
# hostname
[hostname]
ssh_only = false
format = '[[ î‰º ](bold #83C092)[$hostname](bold #A7C080) ]($style)'
#----------------------------------------------------------
# Git info
# Current git branch
[git_branch]
symbol = "ï˜"
format = '[î‰º  \[ $symbol $branch \] ](#A6B0A0 bold)'
# Current git status
[git_status]
format = '[(î‰º \[ $all_status$ahead_behind \]) ](#708089 bold)'
#----------------------------------------------------------
# Command duration / timer
[cmd_duration]
min_time = 75
format = '[$duration](#9DA9A0)'
#----------------------------------------------------------
# Bar extender
[fill]
symbol = ' '
#----------------------------------------------------------
# Time display
[time]
disabled = false
time_format = "%R"
style = "bold white"
format = '[ ïº $time](bold #A6B0A0)'
#----------------------------------------------------------
# Line break / next line
[line_break]
disabled = false
#----------------------------------------------------------
# Current directory / pwd
[directory]
style = "#83C092 bold"
format = "[$path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"
#----------------------------------------------------------
# Chevron / command indicator
[character]
disabled = false
success_symbol = '[>](white)'
error_symbol = '[>](red)'
